"""Static company-profile content injected into every generated proposal,
alongside the client-specific, LLM-written sections. This is NEVER
generated by the LLM — credentials, certifications, and case study
outcomes must be real and verifiable, not synthesized. Edit the values
below once with your actual content; every future proposal reuses them
automatically.

TODO: replace every placeholder (marked with [ ]) before this goes live
for real client-facing proposals.
"""

COMPANY_PROFILE = {
    "company_name": "Elabor8 | A Cprime Company",

    "about_us": (
        "Elabor8 | A Cprime Company is a management consultancy helping organisations "
        "change the way they work through operational design, new ways of "
        "working, and technical excellence. We provide agile consulting, "
        "training, coaching, and advisory services to support capability and "
        "capacity uplift across software delivery, product design and innovation, "
        "customer experience, and technology. Our work focuses on improving "
        "operational efficiency across value streams, strengthening software "
        "lifecycle practices, and sharpening quality engineering and automation. "
        "We operate across Australia and the wider Asia Pacific region."
    ),

    "key_differentiators": [
        "Deep experience in enterprise agility, operational design, and technical excellence.",
        "Atlassian Platinum Partner status through Cprime, with Elabor8 noted as an accredited Gold Partner.",
        "Joint certification as Gold SPCT SAFe consultants.",
        "A transformation approach focused on sustainable change, not disruption.",
    ],

    "credentials": [
        "Recognised in the AFR Fast 100 list six years in a row.",
        "Atlassian Platinum Partner and Elabor8 accredited Gold Partner.",
        "Joint Gold SPCT SAFe consultant certification.",
    ],

    "delivery_methodology_name": "Operational Design, New Ways of Working, and Technical Excellence",
    "delivery_methodology_summary": (
        "Our standard approach combines operational design, ways of working "
        "transformation, and technical enablement to improve how work flows "
        "from strategy through to delivery. We emphasise practical change, "
        "measurable improvement, and capability uplift so changes can be embedded "
        "and sustained."
    ),

    "change_management_principles": [
        "Understand the current state, organisational goals, and constraints before designing change.",
        "Co-design new operating models, ways of working, and communication plans with stakeholders.",
        "Validate and enable through coaching, training, and iterative feedback loops.",
        "Launch with active support, reinforcement, and adoption measures.",
        "Embed improvements through continuous optimisation and capability uplift.",
    ],

    "risk_management_principles": [
        "Structured risk identification and assessment throughout the engagement.",
        "Clear ownership of risks, actions, and mitigations.",
        "Phased delivery to reduce the impact of any single issue.",
        "Ongoing monitoring with practical escalation and recovery paths.",
    ],

    "case_studies": [
        {
            "client": "Global pharmaceutical leader",
            "challenge": (
                "The client needed to streamline IT demand management and improve "
                "end-to-end flow from demand to delivery."
            ),
            "outcome": (
                "Elabor8 | A Cprime Company implemented a demand-to-delivery process using "
                "Apptio Targetprocess integrated with Jira and other systems, helping "
                "the client streamline processes and improve efficiency within three months."
            ),
        },
        {
            "client": "Leading super fund",
            "challenge": (
                "The organisation needed to improve agility, employee engagement, "
                "member acquisition, and project delivery efficiency."
            ),
            "outcome": (
                "Elabor8 | A Cprime Company helped optimise work delivery and improve delivery "
                "performance across the organisation."
            ),
        },
    ],

    "contact_details": {
        "name": "contact@elabor8.com.au",
        "title": "Any questions",
        "email": "contact@elabor8.com.au",
        "phone": "+61 1300 352 278",
    },
}