"""Static company-profile content injected into every generated proposal,
alongside the client-specific, LLM-written sections. This is NEVER
generated by the LLM — credentials, certifications, and case study
outcomes must be real and verifiable, not synthesized. Edit the values
below once with your actual content; every future proposal reuses them
automatically.

TODO: replace every placeholder (marked with [ ]) before this goes live
for real client-facing proposals.
"""

from datetime import date

COMPANY_PROFILE = {
    "company_name": "Elabor8 | A Cprime Company",

    "about_us": (
        "Elabor8 | A Cprime Company is a management consultancy helping organisations "
        "change the way they work through operational design, new ways of "
        "working, and technical excellence. We provide agile consulting, "
        "training, coaching, and advisory services to support capability and "
        "capacity uplift across software delivery, product design and innovation, "
        "customer experience, and technology. Our work focuses on improving "
        "operational efficiency across value streams, strengthening software "
        "lifecycle practices, and sharpening quality engineering and automation. "
        "We operate across Australia and the wider Asia Pacific region."
    ),

    "key_differentiators": [
        "Deep experience in enterprise agility, operational design, and technical excellence.",
        "Atlassian Platinum Partner status through Cprime, with Elabor8 noted as an accredited Gold Partner.",
        "Joint certification as Gold SPCT SAFe consultants.",
        "A transformation approach focused on sustainable change, not disruption.",
    ],

    "credentials": [
        "Recognised in the AFR Fast 100 list six years in a row.",
        "Atlassian Platinum Partner and Elabor8 accredited Gold Partner.",
        "Joint Gold SPCT SAFe consultant certification.",
    ],

    "delivery_methodology_name": "Operational Design, New Ways of Working, and Technical Excellence",
    "delivery_methodology_summary": (
        "Our standard approach combines operational design, ways of working "
        "transformation, and technical enablement to improve how work flows "
        "from strategy through to delivery. We emphasise practical change, "
        "measurable improvement, and capability uplift so changes can be embedded "
        "and sustained."
    ),

    "change_management_principles": [
        "Understand the current state, organisational goals, and constraints before designing change.",
        "Co-design new operating models, ways of working, and communication plans with stakeholders.",
        "Validate and enable through coaching, training, and iterative feedback loops.",
        "Launch with active support, reinforcement, and adoption measures.",
        "Embed improvements through continuous optimisation and capability uplift.",
    ],

    "risk_management_principles": [
        "Structured risk identification and assessment throughout the engagement.",
        "Clear ownership of risks, actions, and mitigations.",
        "Phased delivery to reduce the impact of any single issue.",
        "Ongoing monitoring with practical escalation and recovery paths.",
    ],

    "case_studies": [
        {
            "client": "Optus",
            "challenge": (
                "Optus faced a high-stakes challenge: migrating its mission-critical knowledge base from a legacy system, Knosys, to the modern Atlassian Confluence platform. This system was the central source of truth for its frontline staff, meaning any disruption could directly impact customer service quality. The project was clouded by uncertainty, with significant technical unknowns about the legacy platform that made it difficult to scope the effort. The team needed to navigate the migration of approximately 3,000 pages of content while determining if the project was a simple platform shift or a broader transformation requiring content optimisation and user training. The primary goal was to successfully execute this complex transition without undermining the efficiency of their customer-facing teams."
            ),
            "solution": (
                "To navigate the ambiguity and de-risk the project, Cprime Elabor8 introduced a two week, Agile-based preparatory sprint called 'Phase Zero.' This initial phase was designed to build a strong foundation before committing to the full-scale migration. The solution began with deep discovery workshops involving key stakeholders to map out requirements and understand the system's current use. From there, the team executed a small-scale proof-of-concept (POC) migration. This practical test was crucial for validating the technical approach and uncovering potential issues in a safe environment. The insights gained were then used to design the target state in Confluence and create a detailed, production-ready plan for a pilot migration (currently being executed)."
            ),
            "outcome": (
                "To navigate the ambiguity and de-risk the project, Cprime Elabor8 introduced a two week, Agile-based preparatory sprint called 'Phase Zero.' This initial phase was designed to build a strong foundation before committing to the full-scale migration. The solution began with deep discovery workshops involving key stakeholders to map out requirements and understand the system's current use. From there, the team executed a small-scale proof-of-concept (POC) migration. This practical test was crucial for validating the technical approach and uncovering potential issues in a safe environment. The insights gained were then used to design the target state in Confluence and create a detailed, production-ready plan for a pilot migration (currently being executed)."
                "Clarity on Scope and Effort: The full scope, timeline, and resource requirements for the migration were accurately defined."
                "Proactive Issue Resolution: Potential technical and adoption challenges were identified and mitigated before they could impact the main project."
            ),
            "testimonial": (
                "'The Phase Zero approach was invaluable. It allowed us to understand the complexities of our legacy system and plan a migration that would not disrupt our customer service operations. The team’s expertise and structured methodology gave us confidence in the success of the project.' — Optus Project Lead."
            ),
        },
        {
            "client": "PayPal: The Largest Atlassian Cloud Migration in History",
            "challenge": (
                "Developer experiences hurdles: Over 35,000 active users faced slow performance, limited new features, and complex, outdated interfaces."
                "Cost and efficiency issues: High total cost of ownership and reliance on inefficient, manual processes drove up maintenance expenses and decreased operational efficiency."
                "Scalability and flexibility barriers: Legacy infrastructure could not scale to meet demand spikes or easily adapt to PayPal’s evolving requirements, limiting business agility."
            ),
            "solution": (
                "Comprehensive cloud migration: We executed a detailed phased migration plan, including infrastructure assessment, risk management, and resource allocation, to minimise disruption and maximise efficiency."
                "Workflow transformation: Transformed and scripted over 1,200 individually customised workflows and add-ons, ensuring seamless Day 1 operation and continuous optimisation post-migration."
                "Close partnership and continuous improvement: We worked with Atlassian and PayPal worked collaboratively holding regular status meetings and making iterative improvements, especially enhancing the Confluence migration experience for end-users."
            ),
            "outcome": (
                "Enhanced developer experience for 35,000+ active users with improved flexibility, automation, and access to cloud features."
                "Massive data migration completed: 3,000+ Jira projects, 3.5 million issues, 13,000 Confluence spaces, and 14 million pages—all migrated in a single weekend."
                "Improved operational efficiency, real-time reporting, faster decision-making, and adoption of agile practices leading to quicker time-to-market for new products."
                "Set a benchmark for large-scale Atlassian Cloud migrations, enabling PayPal’s future innovation and growth with a robust, efficient, and scalable foundation."
            ),
            "testimonial": (
                "'The structured approach to prioritising and managing the migration helped dissipate doubts about the suitability of the cloud for PayPal. The process was a journey of continuous improvements, ultimately leading to a successful migration.' — PayPal Engineering Executive."
            ),
        },
    ],

    "contact_details": {
        "name": "Elabor8, A Cprime Company",
        "title": "Any questions",
        "address": "Level 14/175 Pitt St, Sydney NSW 2000",
        "phone": "+61 1300 352 278",
        "email": "contact@elabor8.com",
        "website": "https://elabor8.com.au",
        "date": date.today().isoformat(),
    },
}